import { spawn } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import type { TruecanvasConfig } from "../core/config.js";
import { nodeBin, toolEnv } from "../core/pm.js";

/*
 * The real site for a share link: the app built as static files, so clients
 * scroll and click the actual pages, animations included, instead of frozen
 * copies. The review site hosts the build on a host of its own.
 *
 * Next: the project is copied (without node_modules, the generated canvas
 * route and the canvases) into `.truecanvas/live-export`, a folder inside the
 * project so its node_modules resolve, and built there with `output: "export"`.
 * The dev server keeps running untouched. Vite: `vite build` into that folder.
 * Pages that need a server (API routes, middleware, dynamic routes without
 * generateStaticParams) can't be exported: the build fails and the link keeps
 * its frozen frames.
 */

/** Files and folders never copied into the export. */
const SKIP = new Set(["node_modules", ".next", ".git", ".truecanvas", "out", ".turbo", ".vercel", ".swc", "pnpm-lock.yaml", "package-lock.json", "yarn.lock", "bun.lock", "bun.lockb"]);
const CONFIGS = ["next.config.ts", "next.config.mts", "next.config.mjs", "next.config.js", "next.config.cjs"];

export interface ExportResult {
  /** the static site, ready to upload */
  dir: string;
  /** removes the build once it's uploaded */
  cleanup(): void;
}

export function canExport(config: TruecanvasConfig) {
  return config.framework === "next" || config.framework === "vite";
}

export async function exportSite(config: TruecanvasConfig): Promise<ExportResult> {
  const root = config.root;
  if (config.framework === "vite") {
    // outside the generated route folder (.truecanvas), which the dev server watches
    const out = path.join(root, "node_modules", ".cache", "truecanvas", "live-export");
    const cleanup = () => fs.rmSync(out, { recursive: true, force: true });
    try {
      await run(root, bin(root, "vite", "bin/vite.js"), ["build", "--outDir", out, "--emptyOutDir"]);
      return { dir: out, cleanup };
    } catch (err) {
      cleanup();
      throw err;
    }
  }
  const work = path.join(root, ".truecanvas", "live-export");
  fs.rmSync(work, { recursive: true, force: true });
  fs.mkdirSync(work, { recursive: true });
  // keep the folder out of git even when .truecanvas isn't ignored
  const ignore = path.join(root, ".truecanvas", ".gitignore");
  if (!fs.existsSync(ignore)) fs.writeFileSync(ignore, "# Truecanvas: generated files\n*\n");
  const cleanup = () => fs.rmSync(work, { recursive: true, force: true });
  try {
    copyProject(config, work);
    wrapConfig(work);
    await run(work, bin(root, "next", "dist/bin/next"), ["build"]);
    const out = path.join(work, "out");
    if (!fs.existsSync(path.join(out, "index.html"))) throw new Error("The build finished without a static site (no out/index.html).");
    return { dir: out, cleanup };
  } catch (err) {
    cleanup();
    throw err;
  }
}

function copyProject(config: TruecanvasConfig, work: string) {
  const root = config.root;
  const leaveOut = new Set([config.routeDir, config.canvasDir].map((p) => path.normalize(p)));
  // entry by entry: the export folder is inside the project
  for (const name of fs.readdirSync(root)) {
    if (SKIP.has(name) || leaveOut.has(name)) continue;
    fs.cpSync(path.join(root, name), path.join(work, name), {
      recursive: true,
      filter: (src) => path.basename(src) !== "node_modules" && !leaveOut.has(path.normalize(path.relative(root, src))),
    });
  }
  // server-only parts a static site can't have
  const appDir = path.join(work, config.appDir);
  fs.rmSync(path.join(appDir, "api"), { recursive: true, force: true });
  for (const dir of [work, path.join(work, "src")]) for (const f of ["middleware.ts", "middleware.js", "proxy.ts", "proxy.js"]) fs.rmSync(path.join(dir, f), { force: true });
}

/** The project's next.config, wrapped to build a static export (types aren't checked: it's a preview). */
function wrapConfig(work: string) {
  const found = CONFIGS.find((f) => fs.existsSync(path.join(work, f)));
  const ts = found ? /\.m?ts$/.test(found) : true;
  let imports = "const base = {};";
  if (found) {
    const renamed = `next.config.truecanvas-base${path.extname(found)}`;
    fs.renameSync(path.join(work, found), path.join(work, renamed));
    // a static import with its extension: Next transpiles next.config.ts and its imports this way
    imports = `import base from "./${renamed}";`;
  }
  const body = `// @ts-nocheck
// Generated by Truecanvas: the project's config, built as a static site for a share link.
${imports}
export default async function config(phase, ctx) {
  let c = base;
  if (typeof c === "function") c = await c(phase, ctx);
  const { rewrites, redirects, headers, ...rest } = c ?? {};
  return { ...rest, output: "export", typescript: { ...rest.typescript, ignoreBuildErrors: true }, images: { ...rest.images, unoptimized: true } };
}
`;
  fs.writeFileSync(path.join(work, ts ? "next.config.ts" : "next.config.mjs"), body);
}

/** A package's CLI from the project's node_modules, run with the current Node. */
function bin(root: string, pkg: string, file: string) {
  const p = path.join(root, "node_modules", pkg, file);
  if (!fs.existsSync(p)) throw new Error(`Couldn't find ${pkg} in ${path.join(root, "node_modules")}. Install the project's dependencies first.`);
  return p;
}

function run(cwd: string, script: string, args: string[]) {
  return new Promise<void>((resolve, reject) => {
    const env = toolEnv({ NODE_ENV: "production", NEXT_TELEMETRY_DISABLED: "1" });
    // the person's Node (in the desktop app, process.execPath is Electron)
    const node = nodeBin();
    if (!node) return reject(new Error("Couldn't find Node.js to build the app."));
    const child = spawn(node, [script, ...args], { cwd, env, stdio: ["ignore", "pipe", "pipe"] });
    const log: string[] = [];
    const keep = (b: Buffer) => {
      for (const line of b.toString().split("\n")) if (line.trim()) log.push(line);
      if (log.length > 40) log.splice(0, log.length - 40);
    };
    child.stdout.on("data", keep);
    child.stderr.on("data", keep);
    const timer = setTimeout(() => child.kill("SIGTERM"), 15 * 60_000);
    child.on("error", (err) => {
      clearTimeout(timer);
      reject(err);
    });
    child.on("close", (code) => {
      clearTimeout(timer);
      if (code === 0) return resolve();
      // the lines that explain it, usually the last error
      const tail = log.filter((l) => !/^\s*(▲|✓|○|ƒ|●|Route|Creating|Collecting|Generating|Finalizing|Linting|Compiled)/.test(l)).slice(-6).join("\n");
      reject(new Error(`The app couldn't be built as a static site:\n${tail || `exit code ${code}`}`));
    });
  });
}
