// Programmatic API: the same engine the editor and the MCP server use.
export { parseCanvas, findNode, findFrame, allNodes } from "./parse.js";
export { CanvasEditor, EditError, attrCode, textCode } from "./edit.js";
export { injectIds } from "./inject.js";
export { Workspace, componentJsx } from "./workspace.js";
export type { Command, Actor, HistoryEntry, WorkspaceEvent } from "./workspace.js";
export { loadConfig } from "./config.js";
export type { TruecanvasConfig, DarkMode } from "./config.js";
export { Catalog } from "./catalog.js";
export { outlineDoc, describeComponent } from "./outline.js";
export { readDesignTokens } from "./tokens.js";
export type * from "./types.js";
export { DEVICES, findDevice } from "./devices.js";
export type { Device } from "./devices.js";
export { frameChanges, writeCompare } from "./compare.js";
export { Comments } from "./comments.js";
export { Git } from "./git.js";
export { ICON_LIBRARIES, iconLibraries, iconLibrary, loadIcons, searchIcons } from "./icons.js";
export type { Icon, IconLibrary } from "./icons.js";
export { shadcnStatus, shadcnRegistry, shadcnAdd, shadcnInit } from "./shadcn.js";
export type { ShadcnStatus } from "./shadcn.js";
export { addVitePlugin, configStatus, initProject, wrapConfigExport } from "./init.js";
export { syncRoute, viteStylesheets } from "./scaffold.js";
export { Shots } from "./shots.js";
export { SHOT_FORMATS, SHOT_SHADERS, SHOT_MOTIONS, SHOT_FPS, newShot, normalizeShot, shotLayout, shotPoseAt, captureHeight, linkScroll, scrollProgress, scrollDuration, SHOT_SCROLL_SPEEDS } from "./shot-model.js";
export type { Shot, ShotFormat, ShotBackdrop, ShotFraming, ShotCrop, ShotMotion, ShotPose } from "./shot-model.js";
