import fs from "node:fs";
import path from "node:path";
import type { TruecanvasConfig } from "./config.js";

export const CANVAS_SUFFIX = ".canvas.tsx";
const ROUTE = "truecanvas";

export function canvasFiles(config: TruecanvasConfig): string[] {
  const dir = path.join(config.root, config.canvasDir);
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir)
    .filter((f) => f.endsWith(CANVAS_SUFFIX))
    .sort((a, b) => canvasNameOf(a).localeCompare(canvasNameOf(b)));
}

export function canvasNameOf(file: string) {
  return path.basename(file).slice(0, -CANVAS_SUFFIX.length);
}

/** Canvas names become file names: letters, digits, - and _ only (never a path). */
export function assertCanvasName(name: string): string {
  if (!/^[a-z0-9][a-z0-9-_]*$/i.test(name)) throw new Error(`Invalid canvas name "${name}". Use letters, digits, - and _.`);
  return name;
}

export function canvasPath(config: TruecanvasConfig, name: string) {
  assertCanvasName(name);
  return path.join(config.root, config.canvasDir, `${name}${CANVAS_SUFFIX}`);
}

function writeIfChanged(file: string, content: string) {
  if (fs.existsSync(file) && fs.readFileSync(file, "utf8") === content) return false;
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, content);
  return true;
}

/**
 * Generates the dev-only render route `/truecanvas/[canvas]` in the app and
 * a registry that lazily imports each canvas. Idempotent.
 */
export function syncRoute(config: TruecanvasConfig): boolean {
  const routeDir = path.join(config.root, config.appDir, ROUTE);
  const pageFile = path.join(routeDir, "[canvas]", "page.tsx");
  const registryFile = path.join(routeDir, "canvases.tsx");
  const canvasDirAbs = path.join(config.root, config.canvasDir);
  let rel = path.relative(routeDir, canvasDirAbs);
  if (!rel.startsWith(".")) rel = `./${rel}`;

  const compareDir = path.join(routeDir, "compare");
  const compares = fs.existsSync(compareDir) ? fs.readdirSync(compareDir).filter((f) => f.endsWith(CANVAS_SUFFIX)) : [];
  const entries = [
    ...canvasFiles(config).map((f) => `  ${JSON.stringify(canvasNameOf(f))}: lazy(() => import(${JSON.stringify(`${rel}/${f.replace(/\.tsx$/, "")}`)})),`),
    // older versions rendered for Compare
    ...compares.map((f) => `  ${JSON.stringify(`__compare__${canvasNameOf(f)}`)}: lazy(() => import(${JSON.stringify(`./compare/${f.replace(/\.tsx$/, "")}`)})),`),
  ].join("\n");

  const registry = `"use client";
/* eslint-disable */
// Generated by Truecanvas. Do not edit: it is regenerated when canvases are added or removed.
import { lazy } from "react";
import { TruecanvasHost, type HostProps } from "truecanvas/host";
import { components } from "./components";

const canvases = {
${entries}
};

export default function Canvases(props: Omit<HostProps, "canvases" | "components">) {
  return <TruecanvasHost {...props} canvases={canvases} components={components} />;
}
`;

  const dm = config.darkMode;
  const page = `/* eslint-disable */
// Generated by Truecanvas. Dev-only route that renders canvas frames.
import { notFound } from "next/navigation";
import Canvases from "../canvases";

export const dynamic = "force-dynamic";

export default async function TruecanvasFrame({
  params,
  searchParams,
}: {
  params: Promise<{ canvas: string }>;
  searchParams: Promise<Record<string, string | undefined>>;
}) {
  if (process.env.NODE_ENV !== "development") notFound();
  const { canvas } = await params;
  const query = await searchParams;
  return (
    <Canvases
      canvas={canvas}
      frame={query.frame ?? null}
      theme={(query.theme as "light" | "dark" | "system" | undefined) ?? "system"}
      darkMode={${JSON.stringify(dm)}}
    />
  );
}
`;
  const componentsFile = path.join(routeDir, "components.tsx");
  if (!fs.existsSync(componentsFile)) writeIfChanged(componentsFile, componentRegistry(config, []));
  const a = writeIfChanged(registryFile, registry);
  const b = writeIfChanged(pageFile, page);
  return a || b;
}

export const STARTER_CANVAS = `"use client";
import { Canvas, Frame } from "truecanvas";

/*
 * A placeholder page. Replace the Welcome frame with your own components:
 * drag them from Assets, draw frames with F, or ask your agent over MCP.
 * Inline styles keep it readable in any app, with or without Tailwind.
 */
export default function StarterCanvas() {
  return (
    <Canvas>
      <Frame name="Welcome" x={0} y={0} width={1200} height={760}>
        <div
          style={{
            height: "100%",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            fontFamily: "Inter, ui-sans-serif, system-ui, sans-serif",
            color: "light-dark(#1d1d1b, #ededea)",
            backgroundColor: "light-dark(#f6f5f2, #121211)",
            backgroundImage: "radial-gradient(light-dark(rgba(0,0,0,.07), rgba(255,255,255,.06)) 1px, transparent 1px), radial-gradient(circle at 50% 38%, rgba(255,138,92,.16), transparent 55%)",
            backgroundSize: "22px 22px, 100% 100%",
          }}
        >
          <div
            style={{
              width: 520,
              padding: 40,
              borderRadius: 24,
              backgroundColor: "light-dark(#ffffff, #1b1b1a)",
              border: "1px solid light-dark(#e9e8e4, #2a2a28)",
              boxShadow: "0 1px 2px rgba(0,0,0,.04), 0 24px 60px -24px rgba(0,0,0,.25)",
            }}
          >
            <svg width="44" height="44" viewBox="0 0 64 64" aria-hidden>
              <defs>
                <linearGradient id="tc-starter" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="0" stopColor="#ff9466" />
                  <stop offset="1" stopColor="#ea6a3c" />
                </linearGradient>
              </defs>
              <rect width="64" height="64" rx="15" fill="url(#tc-starter)" />
              <path fill="#f6f5f1" fillRule="evenodd" d="M10.5 10.5h43v13.1h-43z M25.5 16.8h13v36.7h-13z" />
            </svg>
            <h1 style={{ margin: "22px 0 6px", fontSize: 26, lineHeight: "32px", fontWeight: 650, letterSpacing: "-0.02em" }}>Your canvas is ready</h1>
            <p style={{ margin: 0, fontSize: 15, lineHeight: "23px", color: "light-dark(#6b6b66, #a3a39d)" }}>
              Everything here is real code from your app. Replace this frame with your own components.
            </p>
            <div style={{ marginTop: 28, display: "flex", flexDirection: "column", gap: 14 }}>
              <div style={{ display: "flex", alignItems: "center", gap: 14, fontSize: 14 }}>
                <span style={{ minWidth: 58, textAlign: "center", padding: "3px 8px", borderRadius: 7, fontSize: 12, fontWeight: 600, backgroundColor: "light-dark(#f3f2ee, #262624)", border: "1px solid light-dark(#e3e1dc, #34342f)" }}>Assets</span>
                <span>Drag a component from your design system onto a frame</span>
              </div>
              <div style={{ display: "flex", alignItems: "center", gap: 14, fontSize: 14 }}>
                <span style={{ minWidth: 58, textAlign: "center", padding: "3px 8px", borderRadius: 7, fontSize: 12, fontWeight: 600, backgroundColor: "light-dark(#f3f2ee, #262624)", border: "1px solid light-dark(#e3e1dc, #34342f)" }}>F</span>
                <span>Draw a frame, or pick an iPhone or desktop size</span>
              </div>
              <div style={{ display: "flex", alignItems: "center", gap: 14, fontSize: 14 }}>
                <span style={{ minWidth: 58, textAlign: "center", padding: "3px 8px", borderRadius: 7, fontSize: 12, fontWeight: 600, color: "#fff", backgroundColor: "#ee7445", border: "1px solid #e0652f" }}>Agent</span>
                <span>Ask: “Build a pricing page with our components”</span>
              </div>
            </div>
          </div>
        </div>
      </Frame>
    </Canvas>
  );
}
`;

/**
 * Lazy imports of every catalog component, so the editor can render a single
 * component for Assets thumbnails at /truecanvas/__preview.
 */
export function componentRegistry(config: TruecanvasConfig, specs: { name: string; file: string; library?: string }[]): string {
  const routeDir = path.join(config.root, config.appDir, ROUTE);
  const lines = specs.map((c) => {
    let from = c.library;
    if (!from) {
      from = path.relative(routeDir, path.join(config.root, c.file)).replace(/\.(tsx|ts|jsx|js)$/, "");
      if (!from.startsWith(".")) from = `./${from}`;
    }
    return `  ${JSON.stringify(c.name)}: lazy(() => import(${JSON.stringify(from)}).then((m) => ({ default: m[${JSON.stringify(c.name)}] }))),`;
  });
  return `"use client";
/* eslint-disable */
// Generated by Truecanvas. Do not edit: it is regenerated when components change.
import { lazy, type ComponentType } from "react";

// any: components with required props are rendered with whatever the preview passes
export const components: Record<string, ComponentType<any>> = {
${lines.join("\n")}
};
`;
}

export function syncComponentRegistry(config: TruecanvasConfig, specs: { name: string; file: string; library?: string }[]) {
  const file = path.join(config.root, config.appDir, ROUTE, "components.tsx");
  return writeIfChanged(file, componentRegistry(config, specs));
}
